'use strict';
let providerData=WorkbenchStore.load(),providerEdit=null,providerModels=[],providerDefault='',providerUndo=null,testProvider=null,testRunning=false;
const providerPresets={custom:{name:'',baseUrl:'',models:[]},deepseek:{name:'DeepSeek',baseUrl:'https://api.deepseek.com/v1',models:['deepseek-chat','deepseek-reasoner']},qwen:{name:'通义',baseUrl:'https://dashscope.aliyuncs.com/compatible-mode/v1',models:['qwen-plus','qwen-turbo']},local:{name:'本机模型',baseUrl:'http://127.0.0.1:1234/v1',models:[]}};
const effortLabels={default:'服务商默认',minimal:'Minimal',low:'Low',medium:'Medium',high:'High',xhigh:'XHigh'};
function commitProviders(){providerData=WorkbenchStore.save(providerData);renderProviders();}
function maskKey(key){if(!key)return '—';return key.length<=8?'••••':key.slice(0,4)+'••••'+key.slice(-4);}
function syncGenerationControls(){const ps=$('generation-provider'),ms=$('generation-model'),es=$('generation-effort');if(!ps||!ms||!es)return;const selected=ps.value||providerData.activeId;ps.replaceChildren();providerData.providers.forEach(p=>ps.append(new Option(p.name,p.id)));ps.value=providerData.providers.some(p=>p.id===selected)?selected:(providerData.activeId||'');const p=providerData.providers.find(x=>x.id===ps.value);ms.replaceChildren();(p?.models||[]).forEach(m=>ms.append(new Option(m.name===m.modelId?m.modelId:`${m.name} · ${m.modelId}`,m.modelId)));if(p)ms.value=p.model;es.replaceChildren(...WorkbenchStore.efforts.map(x=>new Option(effortLabels[x],x)));es.value=p?.effort||'default';refreshInlineModel();}
function generationConfig(){const p=providerData.providers.find(x=>x.id===$('generation-provider').value);if(!p)throw Error('请先在配置 → 模型设置中添加并选用供应商');const model=$('generation-model').value;if(!p.models.some(m=>m.modelId===model))throw Error('请选择有效模型ID');return {endpoint:p.baseUrl,model,key:p.apiKey,format:p.format,effort:$('generation-effort').value};}
function refreshInlineModel(){const p=providerData.providers.find(x=>x.id===$('generation-provider')?.value),m=p?.models.find(x=>x.modelId===$('generation-model')?.value),effort=$('generation-effort')?.value||'default';const summary=$('inline-model-summary'),status=$('generation-model-status');if(summary)summary.textContent=p?`${p.name} · ${m?.modelId||'未选择模型'} · effort ${effortLabels[effort]}`:'尚未配置模型，请前往配置 → 模型设置';if(status)status.textContent=p?(p.apiKey?'本机已保存 API Key':'未保存 API Key；本机免认证接口可直接使用'):'没有可用供应商';}
function renderProviders(){providerData=WorkbenchStore.load();const list=$('provider-list');list.replaceChildren();providerData.providers.forEach(p=>{const card=node('section',undefined,'provider-card'+(p.id===providerData.activeId?' selected':'')),title=node('h3',p.name);if(p.id===providerData.activeId)title.append(node('span','当前使用','badge'));card.append(title,node('p',p.baseUrl,'path small'),node('p',`OpenAI Chat Completions · 默认：${p.model} · effort ${effortLabels[p.effort]} · ${p.models.length} 个模型`,'small muted'),node('p','API Key：'+maskKey(p.apiKey),'small muted'));const actions=node('div',undefined,'provider-actions');for(const [label,fn] of [['选用',()=>{providerData.activeId=p.id;commitProviders();notice('已选用 '+p.name);}],['测试',()=>openProviderTest(p)],['编辑',()=>editProvider(p)],['删除',()=>{if(!confirm(`确定删除「${p.name}」？将同时清除本机保存的 API Key。`))return;providerUndo=structuredClone(providerData);providerData.providers=providerData.providers.filter(x=>x.id!==p.id);commitProviders();notice('已移除供应商，可在列表下方撤销。');}]]){const b=node('button',label,'subtle');b.onclick=()=>{try{fn();}catch(e){notice(e.message);}};if(label==='选用'&&p.id===providerData.activeId)b.disabled=true;actions.append(b);}card.append(actions);list.append(card);});if(!providerData.providers.length)list.append(node('p','尚未保存供应商。添加云端兼容接口或本机模型服务。','empty'));if(providerUndo){const undo=node('button','撤销上次删除','secondary');undo.onclick=()=>{providerData=providerUndo;providerUndo=null;commitProviders();};list.append(undo);}syncGenerationControls();}
function renderProviderModels(){const list=$('provider-model-list');list.replaceChildren();providerModels.forEach((m,index)=>{const row=node('div',undefined,'provider-model-row'),radio=node('button',m.modelId===providerDefault?'● 默认':'○ 设为默认','subtle');radio.type='button';radio.onclick=()=>{providerDefault=m.modelId;renderProviderModels();};const id=node('input');id.value=m.modelId;id.maxLength=120;id.setAttribute('aria-label','模型ID');id.oninput=()=>{const old=m.modelId;m.modelId=id.value.trim();if(providerDefault===old)providerDefault=m.modelId;};const name=node('input');name.value=m.name;name.maxLength=120;name.setAttribute('aria-label','模型显示名');name.oninput=()=>m.name=name.value;const context=node('input');context.type='number';context.min='0';context.max='100000000';context.placeholder='上下文窗口';context.value=m.contextWindow||'';context.setAttribute('aria-label','上下文窗口');context.oninput=()=>m.contextWindow=Number(context.value)||0;const remove=node('button','移除','subtle');remove.type='button';remove.onclick=()=>{providerModels.splice(index,1);if(providerDefault===m.modelId)providerDefault=providerModels[0]?.modelId||'';renderProviderModels();};row.append(radio,id,name,context,remove);list.append(row);});}
function editProvider(p=null){providerEdit=p?.id||'new';providerModels=structuredClone(p?.models||[]);providerDefault=p?.model||'';$('settings-model-form').hidden=false;$('provider-form-title').textContent=p?'编辑供应商':'添加供应商';$('provider-name').value=p?.name||'';$('settings-endpoint').value=p?.baseUrl||'';$('provider-api-key').value=p?.apiKey||'';$('settings-provider').value='custom';$('provider-new-models').value='';$('settings-model-status').textContent='';renderProviderModels();$('provider-name').focus();}
function addProviderModels(){for(const id of $('provider-new-models').value.split(/[\s,，、]+/).filter(Boolean)){if(id.length>120)throw Error('模型ID最长120字符');if(!providerModels.some(m=>m.modelId===id))providerModels.push({modelId:id,name:id,contextWindow:0});}providerDefault||=providerModels[0]?.modelId||'';$('provider-new-models').value='';renderProviderModels();}
$('provider-add').onclick=()=>editProvider();$('provider-cancel').onclick=()=>{$('settings-model-form').hidden=true;providerEdit=null;};$('settings-provider').onchange=()=>{const p=providerPresets[$('settings-provider').value];$('provider-name').value=p.name;$('settings-endpoint').value=p.baseUrl;providerModels=p.models.map(modelId=>({modelId,name:modelId,contextWindow:0}));providerDefault=providerModels[0]?.modelId||'';renderProviderModels();};$('provider-add-model').onclick=()=>{try{addProviderModels();}catch(e){notice(e.message);}};$('provider-new-models').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();try{addProviderModels();}catch(error){notice(error.message);}}};
$('settings-model-form').onsubmit=e=>{e.preventDefault();try{if($('provider-new-models').value.trim())addProviderModels();const name=$('provider-name').value.trim(),baseUrl=WorkbenchStore.endpoint($('settings-endpoint').value),apiKey=$('provider-api-key').value.trim();const checked=WorkbenchStore.normalize({providers:[{id:'validate',name,baseUrl,apiKey,models:providerModels,model:providerDefault}]}).providers[0];if(!checked)throw Error('请填写供应商名称并至少添加一个有效模型');const previous=providerData.providers.find(x=>x.id===providerEdit),p={...checked,id:providerEdit==='new'?crypto.randomUUID():providerEdit,effort:previous?.effort||'default'};const i=providerData.providers.findIndex(x=>x.id===p.id);if(i<0){if(providerData.providers.length>=30)throw Error('最多保存30家供应商');providerData.providers.push(p);}else providerData.providers[i]=p;providerData.activeId||=p.id;commitProviders();$('provider-api-key').value='';$('settings-model-form').hidden=true;providerEdit=null;notice('供应商、API Key 与模型已保存到本机。');}catch(error){$('settings-model-status').textContent=error.message;}};
$('generation-provider').onchange=()=>{providerData.activeId=$('generation-provider').value;commitProviders();};$('generation-model').onchange=()=>{const p=providerData.providers.find(x=>x.id===$('generation-provider').value);if(p){p.model=$('generation-model').value;commitProviders();}};$('generation-effort').onchange=()=>{const p=providerData.providers.find(x=>x.id===$('generation-provider').value);if(p){p.effort=$('generation-effort').value;commitProviders();}};
function openProviderTest(p){testProvider=p;$('provider-test-target').textContent=`${p.name} · ${p.model} · ${p.baseUrl}`;$('provider-test-status').textContent=p.apiKey?'将使用本机保存的 API Key。':'未保存 API Key；仅适用于免认证本机服务。';$('provider-test-dialog').showModal();}
$('provider-test-close').onclick=()=>{if(!testRunning)$('provider-test-dialog').close();};$('provider-test-dialog').oncancel=e=>{if(testRunning)e.preventDefault();};$('provider-test-run').onclick=()=>busy($('provider-test-run'),async()=>{testRunning=true;$('provider-test-status').textContent='正在发送固定测试短句，最长等待30秒…';try{const r=await api('/api/model-test',{endpoint:testProvider.baseUrl,model:testProvider.model,key:testProvider.apiKey,format:testProvider.format,effort:testProvider.effort});$('provider-test-status').textContent=`连接成功 · ${r.elapsed_ms} ms · 收到 ${r.characters} 字回复`;}catch(e){$('provider-test-status').textContent='连接失败：'+e.message;}finally{testRunning=false;}});window.addEventListener('storage',e=>{if(e.key===WorkbenchStore.key)renderProviders();});
