// Run against an isolated server: LITHOS_TEST_URL=http://127.0.0.1:8775
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.LITHOS_BROWSER?{executablePath:process.env.LITHOS_BROWSER}:{})});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const base=process.env.LITHOS_TEST_URL;if(!base)throw Error('Set LITHOS_TEST_URL to an isolated test server');
 try{
 await page.goto(base+'/app/knowledge');
 await page.waitForSelector('.kb-tree details');
 const name='界面验收-'+Date.now();
 await page.getByRole('button',{name:'＋ 新建知识笔记',exact:true}).click();
 await page.getByRole('textbox',{name:'知识库内相对目录'}).fill('03_工程实践/开发与部署');
 await page.getByRole('textbox',{name:'笔记标题',exact:true}).fill(name);
 await page.getByRole('button',{name:'创建',exact:true}).click();
 const editor=page.getByRole('textbox',{name:'Markdown 编辑器'});
 await editor.waitFor();
 await editor.fill('# '+name+'\n\n## 验证方法\n\n| 项目 | 结果 |\n| --- | --- |\n| 界面测试 | 通过 |\n\n<script>window.XSS=1</script>\n\n[[无效链接]]');
 await page.getByRole('button',{name:'保存',exact:true}).click();
 await page.getByRole('button',{name:'阅读',exact:true}).click();
 await page.locator('.kb-article table').waitFor();
 assert.equal(await page.locator('.kb-article td').count(),2);
 assert.equal(await page.evaluate(()=>window.XSS),undefined);
 await page.locator('.kb-tools').getByRole('button',{name:'☆ 收藏',exact:true}).click();
 await page.getByRole('button',{name:'历史',exact:true}).click();
 await page.locator('.kb-dialog>button').first().click();
 assert.match(await page.locator('.kb-diff').innerText(),/历史版本/);
 await page.getByRole('button',{name:'恢复为新版本',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('.kb-dialog').open);
 assert.equal(await page.locator('.kb-article table').count(),0);
 await page.getByRole('button',{name:'编辑',exact:true}).click();
 await editor.fill('# 恢复草稿验证\n\n未保存的文字');
 await page.waitForFunction(()=>document.querySelector('.status-bar').textContent.includes('恢复草稿已保护'));
 page.on('dialog',dialog=>dialog.accept());
 await page.reload();
 await page.getByRole('button',{name:'恢复编辑',exact:true}).click();
 assert.match(await editor.inputValue(),/未保存的文字/);
 await page.getByRole('button',{name:'保存',exact:true}).click();
 await page.getByRole('button',{name:'阅读',exact:true}).click();
 await page.getByRole('searchbox',{name:'搜索知识',exact:true}).fill('恢复草稿验证');
 await page.locator('.kb-result').first().waitFor();
 assert.ok((await page.locator('.kb-result').count())>=1);
 await page.locator('.kb-result button').first().click();
 await page.locator('.kb-article h1').waitFor();
 const splitter=page.getByRole('separator',{name:'调整导航宽度'});
 const beforeWidth=Number(await splitter.getAttribute('aria-valuenow'));
 await splitter.focus();await page.keyboard.press('ArrowRight');
 assert.equal(Number(await splitter.getAttribute('aria-valuenow')),Math.min(400,beforeWidth+10));
 await page.screenshot({path:process.env.LITHOS_SCREENSHOT||'knowledge-ui.png',fullPage:true});
 await page.setViewportSize({width:850,height:800});
 await page.getByRole('button',{name:'切换侧栏',exact:true}).click();
 assert.ok(await page.locator('.explorer').isVisible());
 await page.getByRole('button',{name:'切换侧栏',exact:true}).click();
 assert.ok(!(await page.locator('.explorer').isVisible()));
 await page.setViewportSize({width:1440,height:1000});
 await page.getByRole('button',{name:'目录图谱',exact:true}).click();
 await page.locator('.graph-node.file').first().click();
 await page.getByRole('button',{name:'打开为文档标签',exact:true}).click();
 await page.locator('.kb-article').waitFor();
 await page.getByRole('button',{name:'编辑',exact:true}).click();
 await editor.fill('# 本地修改，不能覆盖其他写入');
 await page.evaluate(async()=>{
  const path=document.querySelector('.kb-crumb>span').textContent;
  const doc=await (await fetch('/api/kb/read?path='+encodeURIComponent(path))).json();
  const response=await fetch('/api/kb/save',{method:'POST',headers:{'Content-Type':'application/json','X-Workbench-Token':document.querySelector('meta[name="workbench-token"]').content},body:JSON.stringify({path,revision:doc.revision,content:'# 模拟其他程序修改 '+Date.now()})});
  if(!response.ok)throw Error('Failed to simulate competing write');
 });
 await page.getByRole('button',{name:'保存',exact:true}).click();
 await page.getByRole('heading',{name:'磁盘文件已变化',exact:true}).waitFor();
 assert.match(await page.locator('.kb-diff').innerText(),/模拟其他程序修改/);
 await page.getByRole('button',{name:'加载磁盘版本',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('.kb-dialog').open);
 assert.match(await editor.inputValue(),/模拟其他程序修改/);
 await page.locator('.header [data-view="settings"]').click();
 await page.getByRole('button',{name:'搜索与历史',exact:true}).click();
 await page.getByRole('heading',{name:'搜索索引与历史存储',exact:true}).waitFor();
 await page.locator('[data-setting="models"]').click();
 assert.ok(await page.locator('#setting-models').isVisible());
 await page.locator('.header [data-view="work"]').click();
 assert.ok(await page.locator('#work').isVisible());
 assert.deepEqual(errors,[]);
 console.log('PASS: create, edit, safe Markdown tables, favorite, history restore, crash recovery, indexed search, resizable navigation, narrow viewport; no JS errors');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
